services:
  db:
    image: mariadb:10.11
    container_name: pod_mariadb_dev
    env_file:
      - ../../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    volumes:
      - pod_db_data_dev:/var/lib/mysql
      - ./init_test_db.sql:/docker-entrypoint-initdb.d/init_test_db.sql
    healthcheck:
      test: ["CMD", "scripts/healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../../
      dockerfile: deployment/dev/Dockerfile
    container_name: "pod_api_dev${VERSION}"
    volumes:
      - ../../:/app
      - ../../media:/app/media
    ports:
      - "${EXPOSITION_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_started
    env_file:
      - ../../.env
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      DJANGO_SETTINGS_MODULE: config.django.dev.docker
      ALLOWED_HOSTS: "*"
    command: ["run-server"]
  redis:
    image: redis:7
    container_name: pod_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - pod_redis_data_dev:/data

  celery:
    build:
      context: ../../
      dockerfile: deployment/dev/Dockerfile
    container_name: "pod_celery_dev${VERSION}"
    volumes:
      - ../../:/app
      - ../../media:/app/media
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - ../../.env
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      DJANGO_SETTINGS_MODULE: config.django.dev.docker
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: ["celery", "-A", "config", "worker", "-l", "info"]

volumes:
  pod_db_data_dev:
  pod_redis_data_dev:
