from django.conf.urls import url

from pod.recorder.views import (
    digest_admin_ng_series,
    digest_info_me_json,
    digest_ingest_addAttachment,
    digest_ingest_addCatalog,
    digest_ingest_addDCCatalog,
    digest_ingest_addTrack,
    digest_ingest_createMediaPackage,
    digest_ingest_ingest,
    digest_presenter_post,
    digest_settings_toml,
    digest_available,
    digest_studio_static,
    digest_hosts_json,
    digest_capture_admin,
    digest_capture_admin_configuration,
)

app_name = "recorder_digest"
urlpatterns = [
    url(
        r"^services/hosts.json$",
        digest_hosts_json,
        name="hosts_json",
    ),
    url(
        r"^capture-admin/agents/(?P<name>.+)/configuration$",
        digest_capture_admin_configuration,
        name="capture_admin_config",
    ),
    url(
        r"^capture-admin/agents/(?P<name>.*)$",
        digest_capture_admin,
        name="capture_admin_agent",
    ),
    url(
        r"^admin-ng/series/series.json$",
        digest_admin_ng_series,
        name="admin_ng_series",
    ),
    url(
        r"^services/available.json$",
        digest_available,
        name="services_available",
    ),
    url(
        r"^presenter_post$",
        digest_presenter_post,
        name="presenter_post",
    ),
    url(
        r"^settings.toml$",
        digest_settings_toml,
        name="settings_toml",
    ),
    url(
        r"^info/me.json$",
        digest_info_me_json,
        name="info_me_json",
    ),
    url(
        r"^static/(?P<file>.*)$",
        digest_studio_static,
        name="studio_static",
    ),
    url(
        r"^ingest/createMediaPackage$",
        digest_ingest_createMediaPackage,
        name="ingest_createMediaPackage",
    ),
    url(
        r"^ingest/addDCCatalog$",
        digest_ingest_addDCCatalog,
        name="ingest_addDCCatalog",
    ),
    url(
        r"^ingest/addAttachment$",
        digest_ingest_addAttachment,
        name="ingest_addAttachment",
    ),
    url(
        r"^ingest/addTrack$",
        digest_ingest_addTrack,
        name="ingest_addTrack",
    ),
    url(
        r"^ingest/addCatalog$",
        digest_ingest_addCatalog,
        name="ingest_addCatalog",
    ),
    url(
        r"^ingest/ingest$",
        digest_ingest_ingest,
        name="ingest_ingest",
    ),
]
