# Generated by Django 4.2.18 on 2025-02-14 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hyperlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VideoHyperlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hyperlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_hyperlinks', to='hyperlinks.hyperlink')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_hyperlinks', to='video.video')),
            ],
        ),
    ]
