# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options
# test



deploy:
  stage: deploy
  script:
    - /usr/bin/sshpass -V
    - export SSHPASS=$SUNIEADM
    - /usr/bin/sshpass -e ssh -o stricthostkeychecking=no sunieadm@pod-dev.grenet.fr "sudo su - pod -c 'cd django; git checkout $CI_COMMIT_REF_NAME ; git pull'"
    - /usr/bin/sshpass -e ssh -o stricthostkeychecking=no sunieadm@pod-dev.grenet.fr "sudo service uwsgi-pod restart"
    - /usr/bin/sshpass -e ssh -o stricthostkeychecking=no sunieadm@pod-dev.grenet.fr "sudo service nginx restart"
    - /usr/bin/sshpass -e ssh -o stricthostkeychecking=no sunieadm@pod-dev.grenet.fr "sudo /etc/init.d/celeryd stop"
    - /usr/bin/sshpass -e ssh -o stricthostkeychecking=no sunieadm@pod-dev.grenet.fr "sudo /etc/init.d/celeryd start"
  only:
    - loppins_develop
