[pytest]
DJANGO_SETTINGS_MODULE = config.django.test.docker
python_files = tests.py test_*.py *_tests.py
addopts = --nomigrations --reuse-db
norecursedirs = .tmp .venv venv env .env .git .tox .pytest_cache htmlcov media staticfiles
