= Docker
Nom de l’auteur <farid.aitkarra@univ-lille.fr>
v1.0, 2023-01-18
:toc:
:toc-title: Liste des rubriques
:imagesdir: ./images

== Docker / docker-compose avec volumes sur la machine hôte

=== Conteneur ElasticSearch
http://localhost:9200

==== elasticsearch:6.8.23
===== OS/ARCH
----
OS/ARCH
linux/amd64
----

==== elasticsearch:7.17.7
===== OS/ARCH
----
OS/ARCH
linux/amd64
linux/arm64/v8
----

=== Conteneur Redis
==== OS/ARCH
----
linux/386
linux/amd64
linux/arm/v6
linux/arm/v7
linux/arm64/v8
linux/ppc64le
linux/s390x
----

=== Conteneur Python /  FFMPEG  (esup-pod)

==== OS/ARCH
-----
linux/386
linux/amd64
linux/arm/v7
linux/arm64/v8
-----

===== Configuration
1. Renommer le fichier .env.dev-exemple en .env.dev
2. Renseigner le fichier .env.dev
3. Créer un fichier pod/custom/settings_local.py

Renseignez le fichier pod/custom/settings_local.py comme ceci :
----
# Si ElasticSearch 7
USE_PODFILE = True
EMAIL_ON_ENCODING_COMPLETION = False
SECRET_KEY = "A_CHANGER"
DEBUG = True

ES_VERSION = 7

ES_URL = ['http://elasticsearch:9200/']

CACHES = {
    # … default cache config and others
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
    # Persistent cache setup for select2 (NOT DummyCache or LocMemCache).
    "select2": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}

# Uniquement lors d'environnement conteneurisé
MIGRATION_MODULES = {'flatpages': 'pod.db_migrations'}
----

==== Lancement de la stack esup-pod
- Se positionner à la racine du projet
- Sous windows, devez remplacer make par make.bat

===== Commandes
Force la recompilation des conteneurs (obligatoire au premier lancement ou après un docker-reset)
----
Force la recompilation des conteneurs
$ make docker-build
Suppression des répertoires suivants :
- ./pod/log
- ./pod/static
- ./pod/node_modules
----

Lancement sans recompilation des conteneurs, ni suppressions répertoires ./pod/log, ./pod/static, ./pod/node_modules
----
Force la recompilation des conteneurs
$ make docker-start
----

Attention, il a été constaté que sur un mac, le premier lancement peut prendre plus de 5 minutes. ;)

Vous devriez obtenir ce message une fois esup-pod lancé
----
$ pod-dev-with-volumes        | Superuser created successfully.
----
L'application esup-pod est dès lors disponible via cette URL : localhost:9090

===== Arrêt de la stack
----
$ CTRL+C dans la fenetre depuis laquelle l'application esup-pod a été lancée

OU depuis une autre fenêtre via

$ make docker-stop
----

===== Reset de la stack
Cette commande supprime l'ensemble des données crées depuis le/les conteneur(s) via les volumes montés
----
$ make docker-reset
Suppression des répertoires suivants :
- ./pod/log
- ./pod/media
- ./pod/static
- ./pod/node_modules
- ./pod/db_migrations
- ./pod/db.sqlite3
- ./pod/yarn.lock
----

== HELM / Kubernetes
----
TODO...
----

== (C)  Copyright :
- https://www.esup-portail.org/wiki/display/ES/Installation+de+la+plateforme+Pod+V3
- https://github.com/EsupPortail/Esup-Pod
- https://hub.docker.com/_/debian/tags?page=2