= Docker
Nom de l’auteur <farid.aitkarra@univ-lille.fr>
v1.0, 2023-01-18
:toc:
:toc-title: Liste des rubriques
:imagesdir: ./images

== Docker / docker-compose avec volumes sur la machine hôte

=== Conteneur Python /  FFMPEG  (esup-pod)

==== Environnement local de développement (Linux, windows, TODO apple)

===== Variables d'environnement du conteneur esup-pod
1. Renommer le fichier .env.dev-exemple en .env.dev
2. Renseigner le fichier .env.dev
3. Renommer le fichier requirements-conteneur.txt.example en requirements-conteneur.txt
4. Renseigner le fichier requirements-conteneur.txt
5. Le fichier requirements.txt contient une version elasticsearch (elasticsearch==7.17.7) par défault
5. Renommer le fichier dockerfile-dev-with-volumes/config/elasticsearch/settings_local-7-exemple.py en dockerfile-dev-with-volumes/config/elasticsearch/settings_local-7.py
6. Renseigner le fichier dockerfile-dev-with-volumes/config/elasticsearch/settings_local-7.py

===== Configuration
3. créer un fichier pod/custom/settings_local.py

Renseignez le comme ceci :
----
# Si ElasticSearch 7
ES_VERSION = 7

# URL serveur ElascticSeach
ES_URL = ['http://elasticsearch:9200/']

# URL serveur Redis
CACHES = {
    # … default cache config and others
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
    # Persistent cache setup for select2 (NOT DummyCache or LocMemCache).
    "select2": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}

# Uniquement lors d'environnement conteneurisé
MIGRATION_MODULES = {'flatpages': 'pod.db_migrations'}
----

=== Conteneur ElasticSearch

=== Conteneur Redis

=== Conteneur Portainer.io (facultatif)
----
TODO pour windows, apple
$ docker-compose -f ./docker-compose-portainer-with-volumes.yml -p portainer up
$ docker-compose -f ./docker-compose-portainer-with-volumes.yml -p portainer stop
$ docker-compose -f ./docker-compose-portainer-with-volumes.yml -p portainer down -v
----

=== Lancement de la stack
----
Lancement de la stack
$ docker-compose -f ./docker-compose-dev-with-volumes.yml -p esup-pod up
$ docker-compose -f ./docker-compose-dev-with-volumes.yml -p esup-pod up --build

Arrêt de la stack
$ docker-compose -f ./docker-compose-dev-with-volumes.yml -p esup-pod stop

Suppression de la stack
$ docker-compose -f ./docker-compose-dev-with-volumes.yml -p esup-pod down -v
Des messages d'erreurs peuvent apparaître lors du redémmarrage de la stack :
- Premier utilisateur qui aura tous les pouvoirs sur votre instance (CommandError: Error: That nom d’utilisateur is already taken)


Reset des données
Sous linux (TODO windows, apple)
$ sh dockerfile-dev-with-volumes/reset-local-pod.sh
----

== HELM / Kubernetes
----
TODO...
----

== (C)  Copyright :
- https://www.esup-portail.org/wiki/display/ES/Installation+de+la+plateforme+Pod+V3
- https://github.com/EsupPortail/Esup-Pod
- https://hub.docker.com/_/debian/tags?page=2