# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 12:44
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='lastname / firstname')),
                ('email_address', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='mail')),
                ('role', models.CharField(choices=[('actor', 'actor'), ('author', 'author'), ('designer', 'designer'), ('consultant', 'consultant'), ('contributor', 'contributor'), ('editor', 'editor'), ('speaker', 'speaker'), ('soundman', 'soundman'), ('director', 'director'), ('writer', 'writer'), ('technician', 'technician'), ('voice-over', 'voice-over')], default='author', max_length=200, verbose_name='role')),
                ('weblink', models.URLField(blank=True, null=True, verbose_name='Web link')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name='video')),
            ],
            options={
                'verbose_name': 'Contributor',
                'verbose_name_plural': 'Contributors',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Overlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(editable=False, help_text='Used to access this instance, this "slug" is a short label containing only letters, numbers, underscore or dash top.', max_length=105, unique=True, verbose_name='Slug')),
                ('time_start', models.PositiveIntegerField(default=1, help_text='Start time of the overlay, in seconds.', verbose_name='Start time')),
                ('time_end', models.PositiveIntegerField(default=2, help_text='End time of the overlay, in seconds.', verbose_name='End time')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('position', models.CharField(choices=[('top-left', 'top-left'), ('top', 'top'), ('top-right', 'top-right'), ('right', 'right'), ('bottom-right', 'bottom-right'), ('bottom', 'bottom'), ('bottom-left', 'bottom-left'), ('left', 'left')], default='bottom-right', help_text='Position of the overlay.', max_length=100, null=True, verbose_name='Position')),
                ('background', models.BooleanField(default=True, help_text='Show the background of the overlay.', verbose_name='Show background')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Overlay',
                'verbose_name_plural': 'Overlays',
                'ordering': ['time_start'],
            },
        ),
    ]
