# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='lastname / firstname')),
                ('email_address', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='mail')),
                ('role', models.CharField(choices=[('actor', 'actor'), ('author', 'author'), ('designer', 'designer'), ('consultant', 'consultant'), ('contributor', 'contributor'), ('editor', 'editor'), ('speaker', 'speaker'), ('soundman', 'soundman'), ('director', 'director'), ('writer', 'writer'), ('technician', 'technician'), ('voice-over', 'voice-over')], default='author', max_length=200, verbose_name='role')),
                ('weblink', models.URLField(blank=True, null=True, verbose_name='Web link')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name='video')),
            ],
            options={
                'verbose_name': 'Contributor',
                'verbose_name_plural': 'Contributors',
            },
        ),
    ]
