# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='password',
            field=models.CharField(blank=True,
                                   help_text='Viewing this video will '
                                   + 'not be possible without this password.',
                                   max_length=50,
                                   null=True,
                                   verbose_name='password'),
        ),
    ]
