# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 03:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20180311_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='description_nl_NL',
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='channel',
            name='title_nl_NL',
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='description_nl_NL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='title_nl_NL',
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='theme',
            name='description_nl_NL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='title_nl_NL',
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='type',
            name='description_nl_NL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='title_nl_NL',
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_nl_NL',
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_nl_NL',
            field=models.CharField(
                max_length=250, null=True, verbose_name='Title'),
        ),
    ]
