# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20180310_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100,
                                           unique=True, verbose_name='title')),
                ('slug',
                    models.SlugField(help_text='Used to access this '
                                     + 'instance, the "slug" is a short label '
                                     + 'containing only letters, numbers, '
                                     + 'underscore or dash top.',
                                     max_length=100, unique=True,
                                     verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Disciplines',
                'verbose_name': 'Discipline',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100,
                                           unique=True, verbose_name='title')),
                ('slug',
                    models.SlugField(help_text='Used to access this '
                                     + 'instance, the "slug" is a short label '
                                     + 'containing only letters, numbers, '
                                     + 'underscore or dash top.',
                                     max_length=100, unique=True,
                                     verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Types',
                'verbose_name': 'Type',
            },
        ),
    ]
