#------------------------------------------------------------------------------------------------------------------------------
#  (\___/)
#  (='.'=) Dockerfile elasticsearch
#  (")_(")
#------------------------------------------------------------------------------------------------------------------------------
# Conteneur elasticsearch
ARG ELASTICSEARCH_VERSION=elasticsearch:8.17.3
FROM $ELASTICSEARCH_VERSION
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu

# Default shell to bash:
RUN ln -sf /bin/bash /bin/sh
