#------------------------------------------------------------------------------------------------------------------------------
#  (\___/)
#  (='.'=) Dockerfile elasticsearch
#  (")_(")
#------------------------------------------------------------------------------------------------------------------------------
# Conteneur elasticsearch
ARG ELASTICSEARCH_VERSION
FROM $ELASTICSEARCH_VERSION

HEALTHCHECK --timeout=3s --start-period=60s --start-interval=1s CMD \
    curl --fail --silent http://elasticsearch.localhost:9200/_cluster/health || exit 1

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu

