FROM grafana/docker-puppeteer
# RUN npm install --global --unsafe-perm pa11y-ci
COPY ./dockerfile-dev-with-volumes/pa11y-ci/my-entrypoint-pa11y.sh /tmp/my-entrypoint-pa11y.sh
RUN chmod 755 /tmp/my-entrypoint-pa11y.sh
# ENTRYPOINT ["pa11y-ci", "-c", "/usr/config.json"]
ENTRYPOINT ["bash", "/tmp/my-entrypoint-pa11y.sh"]
