FROM grafana/docker-puppeteer:1.1.0
# RUN npm install --global --unsafe-perm pa11y-ci
COPY ./dockerfile-dev-with-volumes/pa11y-ci/my-entrypoint-pa11y.sh /tmp/my-entrypoint-pa11y.sh
RUN chmod 755 /tmp/my-entrypoint-pa11y.sh

# Default shell to bash:
RUN ln -sf /bin/bash /bin/sh

# ENTRYPOINT ["pa11y-ci", "-c", "/usr/config.json"]
ENTRYPOINT ["bash", "/tmp/my-entrypoint-pa11y.sh"]
