# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titre')),
                ('slug', models.SlugField(editable=False, help_text='Used to access this instance, the "slug" is a short label containing only letters, number, underscore or dash top.', max_length=105, unique=True, verbose_name='slug')),
                ('time_start', models.PositiveIntegerField(default=0, help_text='Start time of the chapter, in seconds.', verbose_name='Start time')),
                ('time_end', models.PositiveIntegerField(default=1, help_text='End time of the chapter, in seconds.', verbose_name='End time')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ['time_start'],
            },
        ),
    ]
