# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name='video'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set([('title', 'time_start', 'time_end')]),
        ),
    ]
