from django.utils.translation import gettext_lazy as _

# http://www.w3schools.com/tags/ref_language_codes.asp
# http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
# http://en.wikipedia.org/wiki/ISO_639-1
ALL_LANG_CHOICES = (
    ("ab", _("Abkhazian")),
    ("aa", _("Afar")),
    ("af", _("Afrikaans")),
    ("sq", _("Albanian")),
    ("am", _("Amharic")),
    ("ar", _("Arabic")),
    ("an", _("Aragonese")),
    ("hy", _("Armenian")),
    ("as", _("Assamese")),
    ("ay", _("Aymara")),
    ("az", _("Azerbaijani")),
    ("ba", _("Bashkir")),
    ("eu", _("Basque")),
    ("bn", _("Bengali (Bangla)")),
    ("dz", _("Bhutani")),
    ("bh", _("Bihari")),
    ("bi", _("Bislama")),
    ("br", _("Breton")),
    ("bg", _("Bulgarian")),
    ("my", _("Burmese")),
    ("be", _("Byelorussian (Belarusian)")),
    ("km", _("Cambodian")),
    ("ca", _("Catalan")),
    ("zh", _("Chinese")),
    ("co", _("Corsican")),
    ("hr", _("Croatian")),
    ("cs", _("Czech")),
    ("da", _("Danish")),
    ("nl", _("Dutch")),
    ("en", _("English")),
    ("eo", _("Esperanto")),
    ("et", _("Estonian")),
    ("fo", _("Faeroese")),
    ("fa", _("Farsi")),
    ("fj", _("Fiji")),
    ("fi", _("Finnish")),
    ("fr", _("French")),
    ("fy", _("Frisian")),
    ("gl", _("Galician")),
    ("gd", _("Gaelic (Scottish)")),
    ("gv", _("Gaelic (Manx)")),
    ("ka", _("Georgian")),
    ("de", _("German")),
    ("el", _("Greek")),
    ("kl", _("Greenlandic")),
    ("gn", _("Guarani")),
    ("gu", _("Gujarati")),
    ("ht", _("Haitian Creole")),
    ("ha", _("Hausa")),
    ("he", _("Hebrew")),
    ("hi", _("Hindi")),
    ("hu", _("Hungarian")),
    ("is", _("Icelandic")),
    ("io", _("Ido")),
    ("id", _("Indonesian")),
    ("ia", _("Interlingua")),
    ("ie", _("Interlingue")),
    ("iu", _("Inuktitut")),
    ("ik", _("Inupiak")),
    ("ga", _("Irish")),
    ("it", _("Italian")),
    ("ja", _("Japanese")),
    ("jv", _("Javanese")),
    ("kn", _("Kannada")),
    ("ks", _("Kashmiri")),
    ("kk", _("Kazakh")),
    ("rw", _("Kinyarwanda (Ruanda)")),
    ("ky", _("Kirghiz")),
    ("rn", _("Kirundi (Rundi)")),
    ("ko", _("Korean")),
    ("ku", _("Kurdish")),
    ("lo", _("Laothian")),
    ("la", _("Latin")),
    ("lv", _("Latvian (Lettish)")),
    ("li", _("Limburgish ( Limburger)")),
    ("ln", _("Lingala")),
    ("lt", _("Lithuanian")),
    ("mk", _("Macedonian")),
    ("mg", _("Malagasy")),
    ("ms", _("Malay")),
    ("ml", _("Malayalam")),
    ("mt", _("Maltese")),
    ("mi", _("Maori")),
    ("mr", _("Marathi")),
    ("mo", _("Moldavian")),
    ("mn", _("Mongolian")),
    ("na", _("Nauru")),
    ("ne", _("Nepali")),
    ("no", _("Norwegian")),
    ("oc", _("Occitan")),
    ("or", _("Oriya")),
    ("om", _("Oromo (Afaan Oromo)")),
    ("ps", _("Pashto (Pushto)")),
    ("pl", _("Polish")),
    ("pt", _("Portuguese")),
    ("pa", _("Punjabi")),
    ("qu", _("Quechua")),
    ("rm", _("Rhaeto-Romance")),
    ("ro", _("Romanian")),
    ("ru", _("Russian")),
    ("sm", _("Samoan")),
    ("sg", _("Sangro")),
    ("sa", _("Sanskrit")),
    ("sr", _("Serbian")),
    ("sh", _("Serbo-Croatian")),
    ("st", _("Sesotho")),
    ("tn", _("Setswana")),
    ("sn", _("Shona")),
    ("ii", _("Sichuan Yi")),
    ("sd", _("Sindhi")),
    ("si", _("Sinhalese")),
    ("ss", _("Siswati")),
    ("sk", _("Slovak")),
    ("sl", _("Slovenian")),
    ("so", _("Somali")),
    ("es", _("Spanish")),
    ("su", _("Sundanese")),
    ("sw", _("Swahili (Kiswahili)")),
    ("sv", _("Swedish")),
    ("tl", _("Tagalog")),
    ("tg", _("Tajik")),
    ("ta", _("Tamil")),
    ("tt", _("Tatar")),
    ("te", _("Telugu")),
    ("th", _("Thai")),
    ("bo", _("Tibetan")),
    ("ti", _("Tigrinya")),
    ("to", _("Tonga")),
    ("ts", _("Tsonga")),
    ("tr", _("Turkish")),
    ("tk", _("Turkmen")),
    ("tw", _("Twi")),
    ("ug", _("Uighur")),
    ("uk", _("Ukrainian")),
    ("ur", _("Urdu")),
    ("uz", _("Uzbek")),
    ("vi", _("Vietnamese")),
    ("vo", _("Volapük")),
    ("wa", _("Wallon")),
    ("cy", _("Welsh")),
    ("wo", _("Wolof")),
    ("xh", _("Xhosa")),
    ("yi", _("Yiddish")),
    ("yo", _("Yoruba")),
    ("zu", _("Zulu")),
)

PREF_LANG_CHOICES = (
    ("de", _("German")),
    ("en", _("English")),
    ("ar", _("Arabic")),
    ("zh", _("Chinese")),
    ("es", _("Spanish")),
    ("fr", _("French")),
    ("it", _("Italian")),
    ("ja", _("Japanese")),
    ("ru", _("Russian")),
)
