# Generated by Django 5.2.8 on 2025-12-08 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sites', '0002_alter_domain_unique'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', help_text='Readable name of the group.', max_length=128)),
                ('code_name', models.CharField(help_text='Unique identifier code (e.g., LDAP group name).', max_length=250, unique=True)),
                ('auto_sync', models.BooleanField(default=False, help_text='If True, this group is automatically managed via external auth (CAS/LDAP).', verbose_name='Auto synchronize')),
                ('sites', models.ManyToManyField(help_text='Sites accessible by this group.', to='sites.site')),
            ],
            options={
                'verbose_name': 'Access Group',
                'verbose_name_plural': 'Access Groups',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='GroupSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('sites', models.ManyToManyField(to='sites.site')),
            ],
            options={
                'verbose_name': 'Group site',
                'verbose_name_plural': 'Groups site',
                'ordering': ['group'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(choices=[('local', 'local'), ('CAS', 'CAS'), ('OIDC', 'OIDC'), ('Shibboleth', 'Shibboleth')], default='local', max_length=20, verbose_name='Authentication Type')),
                ('affiliation', models.CharField(choices=[('student', 'student'), ('faculty', 'faculty'), ('staff', 'staff'), ('employee', 'employee'), ('member', 'member'), ('affiliate', 'affiliate'), ('alum', 'alum'), ('library-walk-in', 'library-walk-in'), ('researcher', 'researcher'), ('retired', 'retired'), ('emeritus', 'emeritus'), ('teacher', 'teacher'), ('registered-reader', 'registered-reader')], default='student', max_length=50, verbose_name='Affiliation')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('hashkey', models.CharField(blank=True, default='', help_text='Unique hash generated from username and secret key.', max_length=64, unique=True)),
                ('establishment', models.CharField(blank=True, choices=[('Etab_1', 'Etab_1'), ('Etab_2', 'Etab_2')], default='Etab_1', max_length=10, verbose_name='Establishment')),
                ('accepts_notifications', models.BooleanField(default=None, help_text='Receive push notifications on your devices.', null=True, verbose_name='Accept notifications')),
                ('accessgroups', models.ManyToManyField(blank=True, related_name='users', to='authentication.accessgroup', verbose_name='Access Groups')),
                ('sites', models.ManyToManyField(related_name='owners', to='sites.site')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('userpicture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.customimagemodel', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'ordering': ['user'],
            },
        ),
    ]
