# Generated by Django 5.2.8 on 2025-12-08 13:32

import src.apps.utils.models.CustomImageModel
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, max_length=255, null=True, upload_to=src.apps.utils.models.CustomImageModel.get_upload_path_files, verbose_name='Image')),
            ],
        ),
    ]
