"""
Esup-Pod - Client for interacting with the Esup-Runner Manager API.

This module provides the RunnerClient class for executing encoding tasks
and downloading results from the runner manager.
"""

import logging
import tempfile
import requests

from typing import Any, Dict
from django.core.files import File

logger = logging.getLogger(__name__)


class RunnerClient:
    """Client for the Esup-Runner Manager API."""

    def __init__(self, url: str, token: str):
        """Initializes the runner client with base URL and API token."""
        self.url = url.rstrip("/")
        self.token = token
        self.headers = {"X-API-Token": self.token}

    def execute_task(
        self,
        video_id: str,
        source_url: str,
        notify_url: str = "",
        parameters: Dict[str, Any] = None,
    ) -> Dict[str, Any]:
        """
        Executes a task on the runner manager.
        """
        endpoint = f"{self.url}/task/execute"

        payload = {
            "etab_name": "Pod",
            "app_name": "Pod",
            "app_version": "5.0.0",
            "task_type": "encoding",
            "source_url": source_url,
            "notify_url": notify_url,
            "parameters": parameters or {},
        }

        try:
            response = requests.post(
                endpoint, json=payload, headers=self.headers, timeout=10
            )
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as e:
            logger.error(
                "Failed to execute task on runner manager: %s",
                e,
                exc_info=True,
            )
            if hasattr(e, "response") and e.response is not None:
                logger.error(
                    "Runner manager response body: %s",
                    e.response.text,
                )
            raise ConnectionError("Runner manager API error: %s" % e)

    def get_task_manifest(self, task_id: str) -> Dict[str, Any]:
        """Retrieve the task manifest containing the paths of the generated files"""
        endpoint = f"{self.url}/task/result/{task_id}"
        response = requests.get(endpoint, headers=self.headers, timeout=10)
        response.raise_for_status()
        return response.json()

    def download_task_file_to_temp(self, task_id: str, file_path: str) -> File:
        """Download a file generated by the runner and return it as a Django file."""
        endpoint = f"{self.url}/task/result/{task_id}/file/{file_path}"
        response = requests.get(endpoint, headers=self.headers, stream=True, timeout=30)
        response.raise_for_status()

        lf = tempfile.NamedTemporaryFile(delete=False)
        for chunk in response.iter_content(chunk_size=8192):
            if chunk:
                lf.write(chunk)
        lf.flush()
        lf.seek(0)

        filename = file_path.split("/")[-1]
        return File(lf, name=filename)


def get_runner_client() -> RunnerClient:
    """Factory to get the configured runner client."""
    from config.env import env

    manager_url = env("ENCODING_MANAGER_URL", default="")
    manager_token = env("ENCODING_MANAGER_TOKEN", default="")
    return RunnerClient(url=manager_url, token=manager_token)
