"""
Esup-Pod - Video defaults.
Source of truth for default values for Video app.
"""

DEFAULT_LICENSE = ""
# Feature Flags
USE_STATS_VIEW = False
VIEW_STATS_AUTH = False
USER_VIDEO_CATEGORY = False
WEBTV_MODE = False
USE_DUPLICATE = False
USE_CUT = False
ALLOW_AUTHENTICATED_UPLOAD = True
CHANNEL_MODE = False
ACTIVE_VIDEO_COMMENT = True

# UI / Display Flags
HIDE_USER_FILTER = False
HIDE_TAGS = False
FORCE_LOWERCASE_TAGS = True
MAX_TAG_LENGTH = 50
NUMBER_TAGS_CLOUD = 20
HIDE_SHARE = False
HIDE_DISCIPLINES = False
HIDE_CURSUS = False
HIDE_TYPES = False
STAFF_ONLY_EDITING = False
HOMEPAGE_SHOWS_PASSWORDED = False

# Cache
CACHE_TIMEOUT = 600

USE_TRANSCRIPTION = False
TRANSCRIPTION_MODEL_PARAM = {}
TRANSCRIPTION_TYPE = "WHISPER"

THIRD_PARTY_APPS = []
USE_PODFILE = False

DEFAULT_DC_COVERAGE = "University name"
DEFAULT_DC_RIGHTS = "BY-NC-SA"

TEMPLATE_VISIBLE_SETTINGS = {
    "TITLE_ETB": "University name",
}

DEFAULT_THUMBNAIL = "img/default_thumbnail.svg"
DEFAULT_TYPE_ID = 1

ACCOMMODATION_YEARS = {}
DEFAULT_YEAR_DATE_DELETE = 2
