# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestConnexionstaff():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_connexionstaff(self):
    self.driver.get("http://localhost:9090/")
    self.driver.find_element(By.XPATH, "//li[@id=\'nav-authentication\']/a/i").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("staff_user")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("user")
    self.driver.find_element(By.XPATH, "//form[@id=\'login-form\']/button").click()
    self.vars["podURL"] = self.driver.execute_script("return document.URL;")
    assert(self.vars["podURL"] == "http://localhost:9090/")
  
