# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLang():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lang(self):
    self.driver.get("http://localhost:9090//")
    self.driver.find_element(By.ID, "pod-param-buttons__button").click()
    element = self.driver.find_element(By.ID, "pod-lang-select")
    actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    self.driver.execute_script("arguments[0].dispatchEvent(new Event('mouseover'));", element)
    self.driver.find_element(By.ID, "pod-lang-select").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    # actions.move_to_element(element, 0, 0).perform()
    self.driver.execute_script("arguments[0].dispatchEvent(new Event('mouseover'));", element)
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item").click()
  
