# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pod.filepicker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=16)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('file', models.FileField(max_length=255, upload_to=pod.filepicker.models.get_upload_path)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filepicker_customfilemodel_created', to='authentication.Owner')),
            ],
            options={
                'verbose_name': 'Fichier',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='CustomImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=16)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('file', models.ImageField(max_length=255, upload_to=pod.filepicker.models.get_upload_path)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filepicker_customimagemodel_created', to='authentication.Owner')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='UserDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Owner', verbose_name='Owner')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='filepicker.UserDirectory')),
                ('users', models.ManyToManyField(blank=True, related_name='users_directory', to='authentication.Owner', verbose_name='Users directory')),
            ],
            options={
                'verbose_name': 'User directory',
                'verbose_name_plural': 'User directories',
            },
        ),
        migrations.AddField(
            model_name='customimagemodel',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filepicker.UserDirectory'),
        ),
        migrations.AddField(
            model_name='customimagemodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filepicker_customimagemodel_modified', to='authentication.Owner'),
        ),
        migrations.AddField(
            model_name='customfilemodel',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filepicker.UserDirectory'),
        ),
        migrations.AddField(
            model_name='customfilemodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filepicker_customfilemodel_modified', to='authentication.Owner'),
        ),
    ]
