# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pod.filepicker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_size', models.PositiveIntegerField(blank=True,
                                                          null=True)),
                ('file_type', models.CharField(blank=True, max_length=16)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('file', models.FileField(
                    upload_to=pod.filepicker.models.get_upload_path)),
                ('created_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='filepicker_customfilemodel_created',
                    to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='filepicker_customfilemodel_modified',
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_modified',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_size', models.PositiveIntegerField(blank=True,
                                                          null=True)),
                ('file_type', models.CharField(blank=True, max_length=16)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('file', models.ImageField(
                    upload_to=pod.filepicker.models.get_upload_path)),
                ('created_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='filepicker_customimagemodel_created',
                    to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='filepicker_customimagemodel_modified',
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_modified',),
                'abstract': False,
            },
        ),
    ]
