# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 08:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import pod.enrichment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
        ('filepicker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrichment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titre')),
                ('slug', models.SlugField(editable=False, help_text='Used to access this instance, the "slug" is a short label containing only letters, numbers, underscore or dash top.', max_length=105, unique=True, verbose_name='slug')),
                ('stop_video', models.BooleanField(default=False, help_text='The video will pause when displaying the enrichment.', verbose_name='Stop video')),
                ('start', models.PositiveIntegerField(default=0, help_text='Start of enrichment display in seconds.', verbose_name='Start')),
                ('end', models.PositiveIntegerField(default=1, help_text='End of enrichment display in seconds.', verbose_name='End')),
                ('type', models.CharField(blank=True, choices=[('image', 'image'), ('richtext', 'richtext'), ('weblink', 'weblink'), ('document', 'document'), ('embed', 'embed')], max_length=10, null=True, verbose_name='Type')),
                ('richtext', ckeditor.fields.RichTextField(blank=True, verbose_name='Richtext')),
                ('weblink', models.URLField(blank=True, null=True, verbose_name='Web link')),
                ('embed', models.TextField(blank=True, help_text='Integrate an external source.', max_length=300, null=True, verbose_name='Embed')),
                ('document', models.ForeignKey(blank=True, help_text='Integrate an document (PDF, text, html)', null=True, on_delete=django.db.models.deletion.CASCADE, to='filepicker.CustomFileModel', verbose_name='Document')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filepicker.CustomImageModel', verbose_name='Image')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name='video')),
            ],
            options={
                'verbose_name': 'Enrichment',
                'verbose_name_plural': 'Enrichments',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='EnrichmentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=pod.enrichment.models.get_upload_path_files, verbose_name='Fichier')),
            ],
        ),
        migrations.CreateModel(
            name='EnrichmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, max_length=255, null=True, upload_to=pod.enrichment.models.get_upload_path_files, verbose_name='Image')),
            ],
        ),
    ]
