---
name: Test Comment PR
on: pull_request

jobs:
  example_comment_pr:
    permissions: write-all
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    #   pull-requests: write
    #   repository-projects: write
    #   issues: write
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

    #   - uses: actions/github-script@v6
    #     with:
    #       script: |
    #         github.rest.issues.createComment({
    #           issue_number: context.issue.number,
    #           owner: context.repo.owner,
    #           repo: context.repo.repo,
    #           body: '👋 Thanks for reporting!'
    #         })
      - name: Add comment to PR
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "blah blah" }'

    #   - name: Comment PR
    #     uses: thollander/actions-comment-pull-request@v2
    #     with:
    #       message: 'Hello world ! :wave:'
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
