---
name: Test Comment PR
on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      issues: write
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: 'Hello world ! :wave:'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
