name: Make sure new PRs are sent to development

on:
  pull_request_target: # Please read https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ before using
    types: [opened, edited]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: main
          exclude: development # Don't prevent going from development -> main
          change-to: development
          comment: |
              Your PR was set to target `main`, PRs should be target `development`
              The base branch of this PR has been automatically changed to `development`, please check that there are no merge conflicts


# ---
# name: Test Comment PR
# on:
#     pull_request_target: # Please read https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ before using
#       types: [opened, edited]

# jobs:
#   example_comment_pr:
#     runs-on: ubuntu-latest
#     permissions: write-all
#     name: An example job to comment a PR
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Comment PR
#         uses: thollander/actions-comment-pull-request@v2
#         with:
#           message: 'Hello world ! :wave:'
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
