---
name: Test Comment PR
on:
    pull_request_target: # Please read https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ before using
      types: [opened, edited]

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    permissions: write-all
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: 'Hello world ! :wave:'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
